// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfjCpxvzFimg2yJe3421NDMZwo7jciVFg',
    appId: '1:84492058400:web:efe6f4a9a6e7111648a145',
    messagingSenderId: '84492058400',
    projectId: 'flutter-qr-code-app',
    authDomain: 'flutter-qr-code-app.firebaseapp.com',
    storageBucket: 'flutter-qr-code-app.appspot.com',
    measurementId: 'G-M38X1HW6D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPHzKQlFo0HmiAZWXQXEHe2HVC52x_hfk',
    appId: '1:84492058400:android:0b40577ce907542948a145',
    messagingSenderId: '84492058400',
    projectId: 'flutter-qr-code-app',
    storageBucket: 'flutter-qr-code-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGjMbBsgg3W1JfS32FBp5oboQBHvexV0s',
    appId: '1:84492058400:ios:b568dee9856d762248a145',
    messagingSenderId: '84492058400',
    projectId: 'flutter-qr-code-app',
    storageBucket: 'flutter-qr-code-app.appspot.com',
    iosBundleId: 'com.example.qrCodeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGjMbBsgg3W1JfS32FBp5oboQBHvexV0s',
    appId: '1:84492058400:ios:b568dee9856d762248a145',
    messagingSenderId: '84492058400',
    projectId: 'flutter-qr-code-app',
    storageBucket: 'flutter-qr-code-app.appspot.com',
    iosBundleId: 'com.example.qrCodeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfjCpxvzFimg2yJe3421NDMZwo7jciVFg',
    appId: '1:84492058400:web:ccb4a9873c2949ea48a145',
    messagingSenderId: '84492058400',
    projectId: 'flutter-qr-code-app',
    authDomain: 'flutter-qr-code-app.firebaseapp.com',
    storageBucket: 'flutter-qr-code-app.appspot.com',
    measurementId: 'G-4PVR0XRJ6W',
  );
}
